function showAppointmentDetails(appointment){
  window.__PRINT_APPOINTMENT = appointment;

  const html = `
    <div class="modal-details">
      <div><strong>Patient:</strong> ${esc(appointment.patient_name || appointment.patient_id || 'N/A')}</div>
      <div><strong>Dentist:</strong> ${esc(appointment.doctor_name || 'N/A')}</div>
      <div><strong>Treatment:</strong> ${esc(appointment.treatment || 'N/A')}</div>
      <div><strong>Date:</strong> ${esc(appointment.date || 'N/A')}</div>
      <div><strong>Time:</strong> ${esc(appointment.time || 'N/A')}</div>
      <div><strong>Status:</strong> ${esc(appointment.status || 'N/A')}</div>
      ${appointment.notes ? `<div><strong>Notes:</strong> ${esc(appointment.notes)}</div>` : ''}
      <div style="margin-top:16px;display:flex;gap:8px;flex-wrap:wrap;">
  <button type="button" onclick="openAppointmentPatient()">Open Patient</button>
  <button type="button" onclick="editAppointment()">Edit</button>
  <button type="button" onclick="cancelAppointment()">Cancel</button>
  <button type="button" onclick="completeAppointment()">Complete</button>
  <button type="button" onclick="printAppointmentSlip()">Print Slip</button>
</div>v>
  `;
  showModal(html, 'Appointment Details');
}

function printAppointmentSlip(){
  const appointment = window.__PRINT_APPOINTMENT;
  if(!appointment){
    showToast('No appointment selected');
    return;
  }

  const html = `
    <!doctype html>
    <html>
    <head>
      <title>Appointment Slip</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 30px; }
        h2 { text-align: center; margin-bottom: 5px; }
        .sub { text-align: center; margin-bottom: 25px; color: #555; }
        .row { margin: 10px 0; font-size: 15px; }
        .label { font-weight: bold; }
        .footer { margin-top: 35px; font-size: 12px; color: #666; text-align: center; }
      </style>
    </head>
    <body>
      <h2>DentCare Pro</h2>
      <div class="sub">Appointment Slip</div>

      <div class="row"><span class="label">Patient:</span> ${esc(appointment.patient_name || appointment.patient_id || 'N/A')}</div>
      <div class="row"><span class="label">Dentist:</span> ${esc(appointment.doctor_name || 'N/A')}</div>
      <div class="row"><span class="label">Treatment:</span> ${esc(appointment.treatment || 'N/A')}</div>
      <div class="row"><span class="label">Date:</span> ${esc(appointment.date || 'N/A')}</div>
      <div class="row"><span class="label">Time:</span> ${esc(appointment.time || 'N/A')}</div>
      <div class="row"><span class="label">Status:</span> ${esc(appointment.status || 'N/A')}</div>
      ${appointment.notes ? `<div class="row"><span class="label">Notes:</span> ${esc(appointment.notes)}</div>` : ''}

      <div class="footer">Generated by DentCare Pro</div>
    </body>
    </html>
  `;

  const win = window.open('', '_blank', 'width=600,height=700');
  win.document.open();
  win.document.write(html);
  win.document.close();
  win.focus();
  win.print();
}